services:
  postgres:
    image: postgres:17.4
    container_name: nyangpt-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nyangpt
    volumes:
      - postgres-data:/var/lib/postgresql/data

  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: nyangpt-api
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/nyangpt
    volumes:
      - ./server:/app
    command: npm run start:dev

volumes:
  postgres-data:
